[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/UNIADMSCREATE"
  to = "/UNIADMSCREATE.html"
  status = 200

[[redirects]]
  from = "/UNIADMSCREATE.html"
  to = "/UNIADMSCREATE.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
